version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Brevin installing nodejs 12...
      - n 16
  pre_build:
    commands:
      - echo Brevin installing dependencies...
      - npm install
  build:
    commands:
      - echo Brevin building...
      - npm run-script build
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - buildspec.yml
    - scripts/**/*


  

  

    