version: 0.2
# ubuntu 16.04
phases:
  install:
    - echo Installing nodejs...
    # install Node
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
    - apt install -y nodejs
    
    - echo Installing npm...
    # install npm
    - apt install npm
  pre_build:
    commands:
    - echo Installing dependencies...
    - npm
  build:
    commands:
    - echo Testing...
    - npm test

    - echo Build...
    - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist